# https://taskfile.dev

version: '3'

includes:
  taskfile: ./app.yml

vars:
  USER_ID: 999
  GROUP_ID: 999

dotenv: ['.env']

tasks:
  default:
    cmds:
      - task: rund
  datadir:
    desc: Create system user and associate with docker group.
    cmds:
      - mkdir -p ./data/
      - sudo chown {{.USER_ID}}:{{.GROUP_ID}} ./data/
      - sudo chmod 755 ./data/
      - sudo chmod g+rws ./data/
  create-dot-env:
    desc: Dump container environment to local file.
    cmds:
      - rm -f .env
      - echo 'DOCKER_IMAGE="simpleapp"' >> .env
      - echo 'DEVICE_NAME="simpleapp"' >> .env
      - echo 'APP_NAME="simpleapp"' >> .env
      - echo 'SYSLOG_ADDRESS="udp://localhost:514"' >> .env
      - echo 'RUN_JAVA_APP="true"' >> .env
  setup:
    deps: [create-dot-env, datadir]
    desc: Generate a usable docker-compose.yml for Docker build.
    preconditions:
      - poetry -V
      - python -V
      - python3 -V
      - test -f yaml_interpol
      - test -f docker-compose.template
    cmds:
      - rm -f docker-compose.yml
      - cp docker-compose.template docker-compose.yml
    generates:
      - docker-compose.yml
  java:
    desc: Build Java artifacts in preparation for container build.
    preconditions:
      - java -version
      - javac -version
      - mvn -v
    cmds:
      - mvn package
  build:
    deps: [setup, java]
    desc: Clean up volume directory and build container image.
    preconditions:
      - test -d ./data/
      - docker-compose -v
    cmds:
      - sudo rm -f ./data/app-std* ./data/cron-std* ./data/supervisor.sock
      - docker-compose build --progress plain
  run:
    deps: [build]
    desc: Run docker container
    preconditions:
      - docker -v
      - docker-compose -v
      - test -f docker-compose.yml
    cmds:
      - docker-compose up
  rund:
    deps: [build]
    desc: Run docker container and detach
    preconditions:
      - docker -v
      - docker-compose -v
      - test -f docker-compose.yml
    cmds:
      - docker-compose up -d
  connect:
    cmd: ./connect_to_app.sh {{.DOCKER_APP}}
